# See https://aka.ms/yaml

trigger:
  tags:
    include:
      - v*

resources:
  containers:
    - container: fedora
      image: ucfconsort.azurecr.io/ucx/fedora:1
      endpoint: ucfconsort_registry

stages:
  - stage: Release
    jobs:
      - job: release
        displayName: Build tarball
        container: fedora
        steps:
          - bash: ./autogen.sh
            displayName: Setup autotools

          - bash: |
              set -eE
              mkdir build && cd build
              gcc --version
              ../contrib/configure-release
              ../contrib/buildrpm.sh -s -t -b
              ls -l
              ls -l rpm-dist
            displayName: Build tarball

          - task: GithubRelease@0
            displayName: Create GitHub Draft Release
            inputs:
              githubConnection: github.com_amaslenn
              repositoryName: openucx/ucx
              action: create
              isDraft: true
              addChangeLog: false
